version: '3.8'

services:
  app:
    build: .
    container_name: laravel-app
    ports:
      - "9000:9000"
      - "8080:8000"
    volumes:
      - .:/var/www
    networks:
      - laravel
    command: sh -c "composer install && php-fpm & php artisan serve --host=0.0.0.0 --port=8000"

  db:
    image: mysql:8.0
    container_name: laravel-db
    environment:
      MYSQL_DATABASE: laravel_ecommerce
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: password
      MYSQL_USER: laravel
    ports:
      - "3306:3306"
    networks:
      - laravel

networks:
  laravel:
    driver: bridge